#!/bin/bash

: "${PROMPT_DELAY_SECS:=900}"
: "${LOG_DIR:="$HOME/.prompter"}"
: "${WORK_START_HOUR:=10}"
: "${WORK_END_HOUR:=18}"

mkdir -p -- "$LOG_DIR"

trello_done=0

while sleep "$PROMPT_DELAY_SECS"; do
    current_hour=$(date +%H)
    if (( current_hour < WORK_START_HOUR )) ||
       (( current_hour > WORK_END_HOUR )); then
        continue
    fi

    filename=$LOG_DIR/$(date +%Y%m%d)
    msg="What did you do in the last $PROMPT_DELAY_SECS seconds?"

    if [[ trello_done != "$(date +%F)" ]]; then
        msg+="\n!!! TRELLO NOT DONE !!!\nIf done, enter 'trello'"
    fi

    input=$(zenity --entry --text "$msg")
    ts=$(date +'[%Y-%m-%d %H:%M:%S]')

    case $input in
        ''|same) : ;; # Same as last, don't print
        *[Tt]rello*) trello_done=$(date +%F) ;;
        *) printf '%s %s\n' "$ts" "$input" >> "$filename" ;;
    esac
done
